---
- name: Deploy instances
  hosts: all
  user: "root"
  tasks:
    - name: Start from scratch
      become: true
      become_user: "app"
      ansible.builtin.file:
        path: ~/manual-deployment
        state: absent

    - name: create deploy directory
      become: true
      become_user: "app"
      ansible.builtin.copy:
        src: ./manual-deployment
        dest: ~/

    - name: stop pm2
      become: true
      become_user: "app"
      shell: /bin/bash -c "source ~/.nvm/nvm.sh && ~/.yarn/bin/pm2 kill && ~/.yarn/bin/pm2 delete all && rm -rf vmlets || echo \"OK\""
      args:
        chdir: ~/manual-deployment

    - name: start provisioning
      become: true
      become_user: "app"
      shell: >
        /bin/bash -c "PATH=$PATH:~/.yarn/bin source ~/.nvm/nvm.sh && cd ~/manual-deployment && tmux new -s provisioning \"bash instance-provisioning.sh && bash\""

