---
- name: Deploy instances
  hosts: all
  user: "root"
  tasks:
    - name: Start from scratch
      become: true
      become_user: "app"
      ansible.builtin.file:
        path: ~/zenswarm
        state: absent

    - name: create deploy directory
      become: true
      become_user: "app"
      git:
       repo: https://github.com/dyne/zenswarm.git
       dest: ~/zenswarm
       clone: yes
       update: yes

    - name: apply patch
      become: true
      become_user: "app"
      shell: >
        sed -i 's/$(hostname)/$(hostname -I)/' manual-deployment/instance-provisioning.sh &&
        sed -i 's/command -v/#command -v/' manual-deployment/instance-provisioning.sh
      args:
        chdir: ~/zenswarm
